frr version 10.5.1
frr defaults traditional
hostname r2
no ipv6 forwarding
!
interface eth1
 ip address 10.0.12.2/30
 ip ospf network point-to-point
!
interface eth2
 ip address 10.0.24.1/30
 ip ospf network point-to-point
!
interface lo
 ip address 2.2.2.2/32
!
router ospf
 ospf router-id 2.2.2.2
 network 2.2.2.2/32 area 0
 network 10.0.12.0/30 area 0
 network 10.0.24.0/30 area 0
!
router bgp 65000
 bgp router-id 2.2.2.2
 neighbor 1.1.1.1 remote-as 65000
 neighbor 1.1.1.1 update-source lo
 !
 address-family ipv4 unicast
  network 2.2.2.2/32
  neighbor 1.1.1.1 activate
 exit-address-family
!
mpls ldp
 router-id 2.2.2.2
 !
 address-family ipv4
  discovery transport-address 2.2.2.2
  !
  interface eth1
  !
  interface eth2
  !
 exit-address-family
!
line vty
!
